### ISSUE TITLE
Repo for enrichr-kg?

### ISSUE THREAD

**Issue by caufieldjh** [MaayanLab/enrichr-kg-issues#18]
Hello Ma’ayan Lab - great work on the Enrichr KG, I just saw the NAR paper.
Is there a public repo for this KG?
The link on the https://maayanlab.cloud/enrichr-kg is a 404 (maybe this repo is still private?)

**Comment by AviMaayan** [comment]
Just made it public... https://github.com/MaayanLab/gene-knowledge-graph Thank you for letting us know about it.
