### ISSUE TITLE
Ambiguous Coloring

### ISSUE THREAD

**Issue by rasakereh** [MaayanLab/enrichr-kg-issues#20]
Each dataset is visualized with a color in Enrichr-KG. However, it happens that different shades might be used in the output (both network and bar views). I checked several things like relevant gene count or significance of q-value and all seemed irrelevant to the shades. I could not figure out the information provided by the shades. It should be included in the legends as well. You can see an instance of different shades of the same color (last two pathways) in the figure below. Let me know if you need the gene set to reproduce the result.
 
<img width="1153" alt="image" src="https://github.com/MaayanLab/enrichr-kg-issues/assets/24264594/3dc866dc-1b27-43f6-ad69-c83385aa639f">

**Comment by jeevangelista** [comment]
fixed this
