### ISSUE TITLE
Send gene list from my own site

### ISSUE THREAD

**Issue by ylippi** [MaayanLab/enrichr-kg-issues#21]
Hi,
Congratulations for this nice enrichr-KG tool!
I am already using enrichr and I included the javascript POST code ( as described in FAQ: https://maayanlab.cloud/Enrichr/help#faq&q=3) to send a gene list from my shinyapp to your enrichr site.

Does this functionality will be accessible for enrichr-KG ?
Does an API will also be proposed?

Many thanks,
Regards
Yannick

**Comment by jeevangelista** [comment]
Hi @ylippi this is actually very doable, all you have to do is send the gene set to enrichr's addList endpoint and sending the userListId to enrichr-kg:

https://maayanlab.cloud/enrichr-kg?userListId=56159007&gene_degree=3&search=true&libraries=[{"library":"ChEA_2022","term_limit":5}]

libraries field is optional in case you want to preselect the libraries.
